#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m 
#SBATCH --time=01:00
#SBATCH --account=eecs498f20_class
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=2

# The application(s) to execute along with its input arguments and options:

if [ "$#" -ne 1 ]; then
    echo "Usage: ./run_tests {program}"
    exit 1
fi

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH


./$1
echo "Passed!"
